// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6UrJCWc5LQbHhU3fpJxz3-yF-LADZ3Fo',
    appId: '1:184877146020:web:9eed33026b54762bf46b31',
    messagingSenderId: '184877146020',
    projectId: 'solar-cleaner-system',
    authDomain: 'solar-cleaner-system.firebaseapp.com',
    databaseURL: 'https://solar-cleaner-system-default-rtdb.firebaseio.com',
    storageBucket: 'solar-cleaner-system.firebasestorage.app',
    measurementId: 'G-44V9QKVN0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd__Bso63-fl8MAC0jM2loIyJzJHaaD8w',
    appId: '1:184877146020:android:5dcd8a746e62634df46b31',
    messagingSenderId: '184877146020',
    projectId: 'solar-cleaner-system',
    databaseURL: 'https://solar-cleaner-system-default-rtdb.firebaseio.com',
    storageBucket: 'solar-cleaner-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe2ixStGn5tKuF5H9W1yWyFwNdetF3aYU',
    appId: '1:184877146020:ios:46f2ff92f7f939ebf46b31',
    messagingSenderId: '184877146020',
    projectId: 'solar-cleaner-system',
    databaseURL: 'https://solar-cleaner-system-default-rtdb.firebaseio.com',
    storageBucket: 'solar-cleaner-system.firebasestorage.app',
    iosBundleId: 'com.example.solarCleanerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe2ixStGn5tKuF5H9W1yWyFwNdetF3aYU',
    appId: '1:184877146020:ios:46f2ff92f7f939ebf46b31',
    messagingSenderId: '184877146020',
    projectId: 'solar-cleaner-system',
    databaseURL: 'https://solar-cleaner-system-default-rtdb.firebaseio.com',
    storageBucket: 'solar-cleaner-system.firebasestorage.app',
    iosBundleId: 'com.example.solarCleanerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6UrJCWc5LQbHhU3fpJxz3-yF-LADZ3Fo',
    appId: '1:184877146020:web:ec28c2ae335d6f08f46b31',
    messagingSenderId: '184877146020',
    projectId: 'solar-cleaner-system',
    authDomain: 'solar-cleaner-system.firebaseapp.com',
    databaseURL: 'https://solar-cleaner-system-default-rtdb.firebaseio.com',
    storageBucket: 'solar-cleaner-system.firebasestorage.app',
    measurementId: 'G-2BFBFHSDDH',
  );
}
